#include <iostream>
#include <fstream>
#include <sstream>
#include "Lexer/Lexer.hpp"
#include "Parser/Parser.hpp"

int main(int argc, char* argv[]) {
    const char* filename = "script.hulk";

    // Check for command line arguments
    for (int i = 1; i < argc; i++) {
        filename = argv[i];
    }

    std::cout << "DEBUG: Opening file: " << filename << std::endl;
    
    // Read file content
    std::ifstream file(filename);
    if (!file.is_open()) {
        std::cerr << "Error opening file: " << filename << std::endl;
        return 1;
    }
    
    std::stringstream buffer;
    buffer << file.rdbuf();
    std::string input = buffer.str();
    file.close();
    
    // Tokenize
    std::cout << "DEBUG: Starting tokenization..." << std::endl;
    Lexer lexer;
    std::vector<Token> tokens = lexer.analyze(input);
    
    std::cout << "DEBUG: Tokens generated: " << tokens.size() << std::endl;
    
    // Print tokens list
    std::cout << "\n=== TOKENS GENERATED BY LEXER ===" << std::endl;
    for (size_t i = 0; i < tokens.size(); ++i) {
        const Token& token = tokens[i];
        std::cout << "Token " << (i + 1) << ": "
                  << "Type=" << tokenTypeToString(token.type)
                  << ", Text=\"" << token.text << "\""
                  << ", Row=" << token.row 
                  << ", Col=" << token.col << std::endl;
    }
    std::cout << "================================\n" << std::endl;

    // Parse
    std::cout << "DEBUG: Starting parsing..." << std::endl;
    Parser::Parser parser;

    // Parse tokens into parse tree
    auto parseTree = parser.parse(tokens);

    if (parser.hasErrors()) {
        std::cerr << "Parse errors:" << std::endl;
        for (const auto& error : parser.getErrors()) {
            std::cerr << "  " << error << std::endl;
        }
        return 1;
    }
    
    if (!parseTree) {
        std::cerr << "Failed to parse program" << std::endl;
        return 1;
    }
    
    // Print parse tree (derivation tree)
    std::cout << "\n=== PARSE TREE (DERIVATION TREE) ===" << std::endl;
    parseTree->print();
    std::cout << "===================================\n" << std::endl;

    std::cout << "✓ Syntax analysis completed successfully!" << std::endl;
    std::cout << "✓ Derivation tree generated successfully!" << std::endl;

    return 0;
}

